services:
  remote:
    volumes:
      - $HOME/.config/nvim:/root/.config/nvim
      - $HOME/.config/github-copilot/:/root/.config/github-copilot/
      - $HOME/.zshrc:/root/.zshrc
      - $HOME/.p10k.zsh:/root/.p10k.zsh
      - $HOME/.tmux.conf:/root/.tmux.conf
      - $HOME/.gitconfig:/root/.gitconfig
version: "3.8"
