name: Build and Push

on:
  push:

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ vars.DOCKER_REPO }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Env File
        run: printenv | grep -v "^\(PWD\|SHLVL\|HOME\)" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: DOCKERHUB_USERNAME
          password: DOCKERHUB_TOKEN

      - name: Build all images
        run: ./remote.py build-all

      - name: Push al images
        run: ./remote.py push-all
